server:
  port: 8089

bezkoder:
  openapi:
    dev-url: http://localhost:8089
    prod-url: http://117.6.133.148:8089/

predict:
  url: http://ptitsignlanguage.edu.vn/signlanguage/predict
  api-key: W8W6K-3N7KK-PXB9H-8TD8W-BWTH9

spring:
  datasource:
    url: jdbc:postgresql://117.6.133.148:5433/sign_language
    username: sign_language
    password: sign_language
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: SignLanguage
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

application:
  security:
    jwt:
      secret-key: 531c7c9f715b0e4b92d14a0f9599a3fa1e91cb83d7836a34ec0e030ecedb218d
      expiration: 1800000 # 30 minutes
      refresh-token:
        expiration: 43200000 # 6 hours

logging:
  level:
    org:
    springframework:
      security: DEBUG
      web: DEBUG
      data: DEBUG
      hibernate: DEBUG
      jpa: DEBUG
      sql: DEBUG
      jwt: DEBUG
      bezkoder: DEBUG